# Path to your Python launcher and the package
$pythonw = (Get-Command python.exe).Source -replace 'python\.exe$', 'pythonw.exe'

# Day and night times — adjust to taste
$dayTime   = "7:00am"
$nightTime = "7:00pm"

$dayHour   = ([datetime]$dayTime).Hour
$nightHour = ([datetime]$nightTime).Hour

# --- Write the login picker script alongside this one ---
$scriptDir   = Split-Path -Parent $MyInvocation.MyCommand.Path
$loginScript = Join-Path $scriptDir "ambient-login-picker.ps1"

@"
# Auto-generated by setup-ambient-schedule.ps1
# Picks the day or night preset based on the current hour.
`$h = (Get-Date).Hour
if (`$h -ge $dayHour -and `$h -lt $nightHour) {
    & '$pythonw' -m roboblq_light preset day
} else {
    & '$pythonw' -m roboblq_light preset night
}
"@ | Set-Content -Path $loginScript -Encoding UTF8

# Common settings
$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable

# --- Day task ---
$dayAction = New-ScheduledTaskAction `
    -Execute $pythonw `
    -Argument "-m roboblq_light preset day"

Register-ScheduledTask `
    -TaskName "AmbientLight-Day" `
    -Action $dayAction `
    -Trigger (New-ScheduledTaskTrigger -Daily -At $dayTime) `
    -Settings $settings `
    -RunLevel Limited `
    -Force | Out-Null

# --- Night task ---
$nightAction = New-ScheduledTaskAction `
    -Execute $pythonw `
    -Argument "-m roboblq_light preset night"

Register-ScheduledTask `
    -TaskName "AmbientLight-Night" `
    -Action $nightAction `
    -Trigger (New-ScheduledTaskTrigger -Daily -At $nightTime) `
    -Settings $settings `
    -RunLevel Limited `
    -Force | Out-Null

# --- Login task: invokes the picker script ---
$loginAction = New-ScheduledTaskAction `
    -Execute "powershell.exe" `
    -Argument "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$loginScript`""

$loginTrigger = New-ScheduledTaskTrigger -AtLogon -User $env:USERNAME
$loginTrigger.Delay = "PT15S"

Register-ScheduledTask `
    -TaskName "AmbientLight-Login" `
    -Action $loginAction `
    -Trigger $loginTrigger `
    -Settings $settings `
    -RunLevel Limited `
    -Force | Out-Null

Write-Host ""
Write-Host "Three tasks registered:" -ForegroundColor Green
Write-Host "  AmbientLight-Day    -- daily at $dayTime"
Write-Host "  AmbientLight-Night  -- daily at $nightTime"
Write-Host "  AmbientLight-Login  -- at logon, picks correct preset"
Write-Host ""
Write-Host "Login picker script: $loginScript"
Write-Host "View / edit / disable in Task Scheduler (taskschd.msc)."