"""
ROBOBLOQ light strip wire protocol.

This module contains pure, side-effect-free functions for building the byte
packets that the strip's firmware understands. No HID I/O lives here — see
``device.py`` for that.

Protocol summary
----------------
The strip is a USB HID device (VID 0x1A86, PID 0xFE07) presenting two
interfaces. Interface 0 (MI_00, usage page 0xFF00) is the vendor-defined
data channel where all commands are sent. Interface 1 (MI_01) presents as
a keyboard and is unused for control.

All packets share a common framing:

    +-----+-----+-----+-----+--------+ ... +----------+
    | 'R' | 'B' | LEN |  ID |  CMD   | ... | CHECKSUM |
    +-----+-----+-----+-----+--------+ ... +----------+
       0     1     2     3      4      ...    LEN-1

- Bytes 0-1: literal ASCII "RB" (0x52 0x42), the protocol header.
- Byte 2:    LEN, total packet length in bytes including header and checksum.
- Byte 3:    ID, an 8-bit packet sequence ID generated by the host. Starts at
             1, increments per packet, wraps to 1 after reaching 254.
- Byte 4:    CMD, the action code (see ACTION_* constants).
- Bytes 5..LEN-2: payload, format depends on CMD.
- Byte LEN-1: CHECKSUM, sum of all preceding bytes mod 256.

Reverse-engineered from SyncLight's ``app.asar``. The relevant JS is in the
LIGHT product's protocol class — search for ``setSectionLED``, ``setBrightness``,
etc. in ``.webpack/main/index.js`` after extracting the asar.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, Sequence


# ---------------------------------------------------------------------------
# Device identification
# ---------------------------------------------------------------------------

VENDOR_ID  = 0x1A86   # WCH (Nanjing Qinheng Microelectronics)
PRODUCT_ID = 0xFE07   # ROBOBLOQ "LIGHT"
INTERFACE  = 0        # MI_00, the vendor-defined data channel
USAGE_PAGE = 0xFF00   # vendor-defined usage page on MI_00


# ---------------------------------------------------------------------------
# Frame constants
# ---------------------------------------------------------------------------

HEADER = b"RB"  # 0x52, 0x42 — magic bytes that begin every packet


# ---------------------------------------------------------------------------
# Action codes (byte 4 of the packet)
# ---------------------------------------------------------------------------
# These map directly to the ``action`` object in the firmware-facing protocol
# class. Names match the JS source. Only the codes we actually use today are
# fully documented; the rest are listed for future expansion.

ACTION_SET_SYNC_SCREEN       = 128  # 0x80  screen-sync streaming
ACTION_WRITE_DEVICE_INFO     = 129  # 0x81
ACTION_READ_DEVICE_INFO      = 130  # 0x82
ACTION_READ_DEVICE_UUID      = 131  # 0x83
ACTION_SET_LED_EFFECT        = 133  # 0x85  pre-baked animation effect
ACTION_SET_SECTION_LED       = 134  # 0x86  set per-section static colour
ACTION_SET_BRIGHTNESS        = 135  # 0x87  global brightness 0-100
ACTION_SET_AUTO_OFF          = 137  # 0x89
ACTION_SET_DYNAMIC_SPEED     = 138  # 0x8A  effect speed
ACTION_SET_SOUND_SENSITIVITY = 139  # 0x8B
ACTION_SET_EXTERNAL_AUDIO    = 145  # 0x91
ACTION_SET_OPEN_URL          = 147  # 0x93
ACTION_SET_LAMPS_AMOUNT      = 149  # 0x95  configure section count
ACTION_SET_WHITE_BRIGHT      = 150  # 0x96
ACTION_TURN_OFF_LIGHT        = 151  # 0x97
ACTION_SET_COMPUTER_RHYTHM   = 152  # 0x98


# ---------------------------------------------------------------------------
# Sequence ID generator
# ---------------------------------------------------------------------------

class PacketIdGenerator:
    """
    Replicates SyncLight's ``setID()`` helper — an 8-bit counter starting at
    1, incrementing per call, wrapping to 1 when it reaches 255. The strip
    appears tolerant of the exact value (we have not observed it rejecting
    out-of-order IDs), but matching SyncLight's behaviour is the safest bet.
    """

    __slots__ = ("_id",)

    def __init__(self, start: int = 1) -> None:
        self._id = start

    def next(self) -> int:
        self._id += 1
        if self._id >= 255:
            self._id = 1
        return self._id

    @property
    def current(self) -> int:
        return self._id


# A module-level default generator so simple callers don't have to manage one.
_default_id_gen = PacketIdGenerator()


# ---------------------------------------------------------------------------
# Checksum
# ---------------------------------------------------------------------------

def checksum(data: bytes | bytearray) -> int:
    """
    Additive 8-bit checksum: sum of all bytes mod 256.

    Matches the JS ``i = e => { let t=0; for(let r=0;r<e.length;r++) t+=e[r];
    return t%256; }`` helper in the firmware protocol class.
    """
    return sum(data) % 256


# ---------------------------------------------------------------------------
# Section primitive
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Section:
    """
    A single LED section in a setSectionLED packet.

    Wire layout (5 bytes):

        +-------+----+----+----+------+
        | INDEX |  R |  G |  B | FLAG |
        +-------+----+----+----+------+

    INDEX is the section number. Empirically, sending a single section with
    index 0 lights all sections of a 3-section strip uniformly, so for the
    common "whole strip one colour" case a single Section(0, r, g, b) suffices.

    FLAG's exact meaning is not yet known. SyncLight always sends 255 (0xFF)
    in this position for static colours and the strip behaves as expected,
    so we default to 255.
    """

    index: int
    r: int
    g: int
    b: int
    flag: int = 0xFF

    def __post_init__(self) -> None:
        for name in ("index", "r", "g", "b", "flag"):
            value = getattr(self, name)
            if not 0 <= value <= 0xFF:
                raise ValueError(f"Section.{name}={value} out of range 0-255")


# ---------------------------------------------------------------------------
# Packet builders
# ---------------------------------------------------------------------------

def _frame(cmd: int, payload: bytes, *, id_gen: PacketIdGenerator | None = None) -> bytes:
    """
    Internal helper: wrap a payload in the standard frame.

        RB | LEN | ID | CMD | <payload> | CHECKSUM

    LEN counts every byte including header and checksum.
    """
    if id_gen is None:
        id_gen = _default_id_gen

    total_len = 5 + len(payload) + 1   # header(2) + len(1) + id(1) + cmd(1) + payload + checksum(1)
    if total_len > 0xFF:
        raise ValueError(f"Packet too long: {total_len} bytes (max 255)")

    pid = id_gen.next()
    body = bytearray(total_len)
    body[0:2] = HEADER
    body[2]   = total_len
    body[3]   = pid
    body[4]   = cmd
    body[5:5 + len(payload)] = payload
    body[total_len - 1] = checksum(body[:total_len - 1])
    return bytes(body)


def build_set_brightness(level: int, *, id_gen: PacketIdGenerator | None = None) -> bytes:
    """
    Build a setBrightness packet.

    :param level: brightness 0-100. Values outside the range are clamped.
    :return: 7-byte packet ready to write to the HID interface.

    Example::

        >>> pkt = build_set_brightness(50)
        >>> pkt.hex(' ').upper()
        '52 42 07 ?? 87 32 ??'   # ID and checksum vary
    """
    level = max(0, min(100, int(level)))
    return _frame(ACTION_SET_BRIGHTNESS, bytes([level]), id_gen=id_gen)


def build_turn_off(*, id_gen: PacketIdGenerator | None = None) -> bytes:
    """
    Build a turnOffLight packet.

    :return: 6-byte packet that switches all LEDs off.
    """
    return _frame(ACTION_TURN_OFF_LIGHT, b"", id_gen=id_gen)


def build_set_section_led(
    sections: Sequence[Section] | Iterable[Section],
    *,
    id_gen: PacketIdGenerator | None = None,
) -> bytes:
    """
    Build a setSectionLED packet for one or more sections.

    :param sections: iterable of Section instances. At least one required.
    :return: variable-length packet, 6 + 5*N bytes.

    The "whole strip, one colour" idiom is::

        build_set_section_led([Section(0, r, g, b)])
    """
    section_list = list(sections)
    if not section_list:
        raise ValueError("at least one section required")

    payload = bytearray(5 * len(section_list))
    for i, s in enumerate(section_list):
        off = 5 * i
        payload[off]     = s.index
        payload[off + 1] = s.r
        payload[off + 2] = s.g
        payload[off + 3] = s.b
        payload[off + 4] = s.flag

    return _frame(ACTION_SET_SECTION_LED, bytes(payload), id_gen=id_gen)


def build_solid_color(r: int, g: int, b: int, *,
                      id_gen: PacketIdGenerator | None = None) -> bytes:
    """
    Convenience builder: set the entire strip to a single RGB colour.

    Equivalent to ``build_set_section_led([Section(0, r, g, b)])``.
    """
    return build_set_section_led([Section(0, r, g, b)], id_gen=id_gen)


# ---------------------------------------------------------------------------
# Decoder (mainly useful for debugging captured packets)
# ---------------------------------------------------------------------------

def decode_packet(data: bytes) -> dict:
    """
    Parse a packet's frame and return a dict of its fields.

    Useful when reverse-engineering captures or verifying that builders
    produce the bytes we expect. Validates header, length, and checksum.
    """
    if len(data) < 6:
        raise ValueError(f"Packet too short: {len(data)} bytes")
    if data[0:2] != HEADER:
        raise ValueError(f"Bad header: {data[0:2]!r} (expected {HEADER!r})")
    declared_len = data[2]
    if declared_len != len(data):
        raise ValueError(
            f"Length mismatch: header says {declared_len}, got {len(data)} bytes"
        )
    expected_checksum = checksum(data[:-1])
    if data[-1] != expected_checksum:
        raise ValueError(
            f"Checksum mismatch: got 0x{data[-1]:02X}, expected 0x{expected_checksum:02X}"
        )
    return {
        "header":   data[0:2],
        "length":   data[2],
        "id":       data[3],
        "cmd":      data[4],
        "payload":  bytes(data[5:-1]),
        "checksum": data[-1],
    }
